services:
  ui-visualgo:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ui-visualgo
    environment:
      NODE_ENV: development
    ports:
      - "5174:5174"
    networks:
      - visualgo-network
networks:
  visualgo-network:
    driver: bridge
